# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='answer_voted_rp', to='preguntas.Usuario'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvotes',
            field=models.ManyToManyField(related_name='question_voted_up', to='preguntas.Usuario'),
        ),
    ]
