# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0002_auto_20160518_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='answer_voted_up', to='preguntas.Usuario'),
        ),
    ]
