# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0003_auto_20160518_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('owner', 'question')]),
        ),
    ]
