# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preguntas', '0004_auto_20160519_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.Usuario')),
                ('parent_answer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Answer')),
                ('parent_question', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='preguntas.Question')),
                ('upvotes', models.ManyToManyField(related_name='comment_voted_up', to='preguntas.Usuario')),
            ],
        ),
    ]
